/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package choiceGUI;

/**
 *
 * @author hsfco
 */
public class premierChoix extends javax.swing.JFrame {

    /**
     * Creates new form premierChoix
     */
    public premierChoix() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gendertitle = new javax.swing.JLabel();
        agetitle = new javax.swing.JLabel();
        smoketitle = new javax.swing.JLabel();
        checkNSP = new javax.swing.JCheckBox();
        checkPGP = new javax.swing.JCheckBox();
        checkTGP = new javax.swing.JCheckBox();
        checkMen = new javax.swing.JCheckBox();
        chekWomen = new javax.swing.JCheckBox();
        age2529 = new javax.swing.JCheckBox();
        checkSmoke = new javax.swing.JCheckBox();
        chekNoSmoke = new javax.swing.JCheckBox();
        age3034 = new javax.swing.JCheckBox();
        age3539 = new javax.swing.JCheckBox();
        age4044 = new javax.swing.JCheckBox();
        age4549 = new javax.swing.JCheckBox();
        age5054 = new javax.swing.JCheckBox();
        age5559 = new javax.swing.JCheckBox();
        generatebutton = new javax.swing.JButton();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));
        setForeground(new java.awt.Color(204, 204, 0));

        gendertitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gendertitle.setText("Gender");

        agetitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agetitle.setText("Age");

        smoketitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        smoketitle.setText("Smoke Habit");

        checkNSP.setText("NSP");

        checkPGP.setText("PGP");

        checkTGP.setText("TGP");

        checkMen.setText("Men");

        chekWomen.setText("Women");

        age2529.setText("25-29");

        checkSmoke.setText("Smoker");

        chekNoSmoke.setText("Non-Smoker");

        age3034.setText("30-34");

        age3539.setText("35-39");

        age4044.setText("40-44");

        age4549.setText("45-49");

        age5054.setText("50-54");

        age5559.setText("55-59");

        generatebutton.setText("Generate");
        generatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatebuttonActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("PREMIUM Generator");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(smoketitle, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(checkSmoke, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkNSP, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(checkPGP, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chekNoSmoke, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chekWomen, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkTGP, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gendertitle, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(checkMen, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agetitle, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(age2529, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(age4549, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(age3034, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(age3539, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(age5559, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(age4044, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addComponent(age5054, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(generatebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(title)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gendertitle)
                    .addComponent(checkMen)
                    .addComponent(chekWomen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(smoketitle)
                        .addComponent(checkSmoke))
                    .addComponent(chekNoSmoke))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkTGP)
                    .addComponent(checkPGP)
                    .addComponent(checkNSP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agetitle)
                    .addComponent(age2529)
                    .addComponent(age3034)
                    .addComponent(age3539))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age4549)
                    .addComponent(age4044)
                    .addComponent(age5054))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(age5559)
                .addGap(37, 37, 37)
                .addComponent(generatebutton)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatebuttonActionPerformed
        
        // condition si MEN - SMOKE - NSP 
        if(checkMen.isSelected() && age2529.isSelected() && checkSmoke.isSelected() && checkNSP.isSelected()){
           new resultat2529().setVisible(true);
            dispose();
        } else if (checkMen.isSelected() && age3034.isSelected() && checkSmoke.isSelected() && checkNSP.isSelected()){
            new resultat3034().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age3539.isSelected() && checkSmoke.isSelected() && checkNSP.isSelected()){
            new resultat3539().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age4044.isSelected() && checkSmoke.isSelected() && checkNSP.isSelected()){
            new resultat4044().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age4549.isSelected() && checkSmoke.isSelected() && checkNSP.isSelected()){
            new resultat4549().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age5054.isSelected() && checkSmoke.isSelected() && checkNSP.isSelected()){
            new resultat5054().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age5559.isSelected() && checkSmoke.isSelected() && checkNSP.isSelected()){
            new resultat5559().setVisible(true);
            dispose();
        }
        
        // CONDITION SI MEN - NOSMOKE - NSP
        if(checkMen.isSelected() && age2529.isSelected() && chekNoSmoke.isSelected() && checkNSP.isSelected()){
           new resultat2529v2().setVisible(true);
            dispose();
        } else if (checkMen.isSelected() && age3034.isSelected() && chekNoSmoke.isSelected() && checkNSP.isSelected()){
            new resultat3034v2().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age3539.isSelected() && chekNoSmoke.isSelected() && checkNSP.isSelected()){
            new resultat3539v2().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age4044.isSelected() && chekNoSmoke.isSelected() && checkNSP.isSelected()){
            new resultat4044v2().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age4549.isSelected() && chekNoSmoke.isSelected() && checkNSP.isSelected()){
            new resultat4549v2().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age5054.isSelected() && chekNoSmoke.isSelected() && checkNSP.isSelected()){
            new resultat5054v2().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age5559.isSelected() && chekNoSmoke.isSelected() && checkNSP.isSelected()){
            new resultat5559v2().setVisible(true);
            dispose();
        }
        
        //CONDITION SI MEN - NO SMOKE PGP
        
        if(checkMen.isSelected() && age2529.isSelected() && chekNoSmoke.isSelected() && checkPGP.isSelected()){
           new resultat2529v3().setVisible(true);
            dispose();
        } else if (checkMen.isSelected() && age3034.isSelected() && chekNoSmoke.isSelected() && checkPGP.isSelected()){
            new resultat3034v3().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age3539.isSelected() && chekNoSmoke.isSelected() && checkPGP.isSelected()){
            new resultat3539v3().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age4044.isSelected() && chekNoSmoke.isSelected() && checkPGP.isSelected()){
            new resultat4044v3().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age4549.isSelected() && chekNoSmoke.isSelected() && checkPGP.isSelected()){
            new resultat4549v3().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age5054.isSelected() && chekNoSmoke.isSelected() && checkPGP.isSelected()){
            new resultat5054v3().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age5559.isSelected() && chekNoSmoke.isSelected() && checkPGP.isSelected()){
            new resultat5559v3().setVisible(true);
            dispose();
        }
        
        // CONDITION SI MEN - NO SMOKE - TGP 
        if(checkMen.isSelected() && age2529.isSelected() && chekNoSmoke.isSelected() && checkTGP.isSelected()){
           new resultat2529v4().setVisible(true);
            dispose();
        } else if (checkMen.isSelected() && age3034.isSelected() && chekNoSmoke.isSelected() && checkTGP.isSelected()){
            new resultat3034v4().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age3539.isSelected() && chekNoSmoke.isSelected() && checkTGP.isSelected()){
            new resultat3539v4().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age4044.isSelected() && chekNoSmoke.isSelected() && checkTGP.isSelected()){
            new resultat4044v4().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age4549.isSelected() && chekNoSmoke.isSelected() && checkTGP.isSelected()){
            new resultat4549v4().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age5054.isSelected() && chekNoSmoke.isSelected() && checkTGP.isSelected()){
            new resultat5054v4().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age5559.isSelected() && chekNoSmoke.isSelected() && checkTGP.isSelected()){
            new resultat5559v4().setVisible(true);
            dispose();
        }
        
        // CONDITION SI MEN - SMOKE - PGP
        if(checkMen.isSelected() && age2529.isSelected() && checkSmoke.isSelected() && checkPGP.isSelected()){
           new resultat2529v5().setVisible(true);
            dispose();
        } else if (checkMen.isSelected() && age3034.isSelected() && checkSmoke.isSelected() && checkPGP.isSelected()){
            new resultat3034v5().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age3539.isSelected() && checkSmoke.isSelected() && checkPGP.isSelected()){
            new resultat3539v5().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age4044.isSelected() && checkSmoke.isSelected() && checkPGP.isSelected()){
            new resultat4044v5().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age4549.isSelected() && checkSmoke.isSelected() && checkPGP.isSelected()){
            new resultat4549v5().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age5054.isSelected() && checkSmoke.isSelected() && checkPGP.isSelected()){
            new resultat5054v5().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age5559.isSelected() && checkSmoke.isSelected() && checkPGP.isSelected()){
            new resultat5559v5().setVisible(true);
            dispose();
        }
        
        // CONDITION SI MEN - SMOKE - TGP
        if(checkMen.isSelected() && age2529.isSelected() && checkSmoke.isSelected() && checkTGP.isSelected()){
           new resultat2529v6().setVisible(true);
            dispose();
        } else if (checkMen.isSelected() && age3034.isSelected() && checkSmoke.isSelected() && checkTGP.isSelected()){
            new resultat3034v6().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age3539.isSelected() && checkSmoke.isSelected() && checkTGP.isSelected()){
            new resultat3539v6().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age4044.isSelected() && checkSmoke.isSelected() && checkTGP.isSelected()){
            new resultat4044v6().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age4549.isSelected() && checkSmoke.isSelected() && checkTGP.isSelected()){
            new resultat4549v6().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age5054.isSelected() && checkSmoke.isSelected() && checkTGP.isSelected()){
            new resultat5054v6().setVisible(true);
            dispose();
        }else if (checkMen.isSelected() && age5559.isSelected() && checkSmoke.isSelected() && checkTGP.isSelected()){
            new resultat5559v6().setVisible(true);
            dispose();
        }
        
        // condition si WOMEN - SMOKE - NSP 
        if(chekWomen.isSelected() && age2529.isSelected() && checkSmoke.isSelected() && checkNSP.isSelected()){
           new resultat2529f().setVisible(true);
            dispose();
        } else if (chekWomen.isSelected() && age3034.isSelected() && checkSmoke.isSelected() && checkNSP.isSelected()){
            new resultat3034f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age3539.isSelected() && checkSmoke.isSelected() && checkNSP.isSelected()){
            new resultat3539f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age4044.isSelected() && checkSmoke.isSelected() && checkNSP.isSelected()){
            new resultat4044f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age4549.isSelected() && checkSmoke.isSelected() && checkNSP.isSelected()){
            new resultat4549f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age5054.isSelected() && checkSmoke.isSelected() && checkNSP.isSelected()){
            new resultat5054f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age5559.isSelected() && checkSmoke.isSelected() && checkNSP.isSelected()){
            new resultat5559f().setVisible(true);
            dispose();
        }
        
        // CONDITION SI WOMEN - NOSMOKE - NSP
        if(chekWomen.isSelected() && age2529.isSelected() && chekNoSmoke.isSelected() && checkNSP.isSelected()){
           new resultat2529v2f().setVisible(true);
            dispose();
        } else if (chekWomen.isSelected() && age3034.isSelected() && chekNoSmoke.isSelected() && checkNSP.isSelected()){
            new resultat3034v2f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age3539.isSelected() && chekNoSmoke.isSelected() && checkNSP.isSelected()){
            new resultat3539v2f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age4044.isSelected() && chekNoSmoke.isSelected() && checkNSP.isSelected()){
            new resultat4044v2f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age4549.isSelected() && chekNoSmoke.isSelected() && checkNSP.isSelected()){
            new resultat4549v2f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age5054.isSelected() && chekNoSmoke.isSelected() && checkNSP.isSelected()){
            new resultat5054v2f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age5559.isSelected() && chekNoSmoke.isSelected() && checkNSP.isSelected()){
            new resultat5559v2f().setVisible(true);
            dispose();
        }
        
        //CONDITION SI WOMEN - NO SMOKE PGP
        
        if(chekWomen.isSelected() && age2529.isSelected() && chekNoSmoke.isSelected() && checkPGP.isSelected()){
           new resultat2529v3f().setVisible(true);
            dispose();
        } else if (chekWomen.isSelected() && age3034.isSelected() && chekNoSmoke.isSelected() && checkPGP.isSelected()){
            new resultat3034v3f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age3539.isSelected() && chekNoSmoke.isSelected() && checkPGP.isSelected()){
            new resultat3539v3f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age4044.isSelected() && chekNoSmoke.isSelected() && checkPGP.isSelected()){
            new resultat4044v3f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age4549.isSelected() && chekNoSmoke.isSelected() && checkPGP.isSelected()){
            new resultat4549v3f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age5054.isSelected() && chekNoSmoke.isSelected() && checkPGP.isSelected()){
            new resultat5054v3f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age5559.isSelected() && chekNoSmoke.isSelected() && checkPGP.isSelected()){
            new resultat5559v3f().setVisible(true);
            dispose();
        }
        
        // CONDITION SI WOMEN - NO SMOKE - TGP 
        if(chekWomen.isSelected() && age2529.isSelected() && chekNoSmoke.isSelected() && checkTGP.isSelected()){
           new resultat2529v4f().setVisible(true);
            dispose();
        } else if (chekWomen.isSelected() && age3034.isSelected() && chekNoSmoke.isSelected() && checkTGP.isSelected()){
            new resultat3034v4f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age3539.isSelected() && chekNoSmoke.isSelected() && checkTGP.isSelected()){
            new resultat3539v4f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age4044.isSelected() && chekNoSmoke.isSelected() && checkTGP.isSelected()){
            new resultat4044v4f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age4549.isSelected() && chekNoSmoke.isSelected() && checkTGP.isSelected()){
            new resultat4549v4f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age5054.isSelected() && chekNoSmoke.isSelected() && checkTGP.isSelected()){
            new resultat5054v4f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age5559.isSelected() && chekNoSmoke.isSelected() && checkTGP.isSelected()){
            new resultat5559v4f().setVisible(true);
            dispose();
        }
        
        // CONDITION SI WOMEN - SMOKE - PGP
        if(chekWomen.isSelected() && age2529.isSelected() && checkSmoke.isSelected() && checkPGP.isSelected()){
           new resultat2529v5f().setVisible(true);
            dispose();
        } else if (chekWomen.isSelected() && age3034.isSelected() && checkSmoke.isSelected() && checkPGP.isSelected()){
            new resultat3034v5f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age3539.isSelected() && checkSmoke.isSelected() && checkPGP.isSelected()){
            new resultat3539v5f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age4044.isSelected() && checkSmoke.isSelected() && checkPGP.isSelected()){
            new resultat4044v5f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age4549.isSelected() && checkSmoke.isSelected() && checkPGP.isSelected()){
            new resultat4549v5f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age5054.isSelected() && checkSmoke.isSelected() && checkPGP.isSelected()){
            new resultat5054v5f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age5559.isSelected() && checkSmoke.isSelected() && checkPGP.isSelected()){
            new resultat5559v5f().setVisible(true);
            dispose();
        }
        
        // CONDITION SI WOMEN - SMOKE - TGP
        if(chekWomen.isSelected() && age2529.isSelected() && checkSmoke.isSelected() && checkTGP.isSelected()){
           new resultat2529v6f().setVisible(true);
            dispose();
        } else if (chekWomen.isSelected() && age3034.isSelected() && checkSmoke.isSelected() && checkTGP.isSelected()){
            new resultat3034v6f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age3539.isSelected() && checkSmoke.isSelected() && checkTGP.isSelected()){
            new resultat3539v6f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age4044.isSelected() && checkSmoke.isSelected() && checkTGP.isSelected()){
            new resultat4044v6f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age4549.isSelected() && checkSmoke.isSelected() && checkTGP.isSelected()){
            new resultat4549v6f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age5054.isSelected() && checkSmoke.isSelected() && checkTGP.isSelected()){
            new resultat5054v6f().setVisible(true);
            dispose();
        }else if (chekWomen.isSelected() && age5559.isSelected() && checkSmoke.isSelected() && checkTGP.isSelected()){
            new resultat5559v6f().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_generatebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(premierChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(premierChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(premierChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(premierChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new premierChoix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox age2529;
    private javax.swing.JCheckBox age3034;
    private javax.swing.JCheckBox age3539;
    private javax.swing.JCheckBox age4044;
    private javax.swing.JCheckBox age4549;
    private javax.swing.JCheckBox age5054;
    private javax.swing.JCheckBox age5559;
    private javax.swing.JLabel agetitle;
    private javax.swing.JCheckBox checkMen;
    private javax.swing.JCheckBox checkNSP;
    private javax.swing.JCheckBox checkPGP;
    private javax.swing.JCheckBox checkSmoke;
    private javax.swing.JCheckBox checkTGP;
    private javax.swing.JCheckBox chekNoSmoke;
    private javax.swing.JCheckBox chekWomen;
    private javax.swing.JLabel gendertitle;
    private javax.swing.JButton generatebutton;
    private javax.swing.JLabel smoketitle;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
